import React from "react";
import {Helmet} from "react-helmet";

const TermsAndConditions = (props) => {
    return(
			<React.Fragment>
        <Helmet>
            <title>Getsetgig | TERMS & CONDITION</title>
        </Helmet>
        <div className="terms">
            <div className="terms-wrapper">
                <div className="terms-container-main">
                    <div className="terms-container">
                        <h1 className="terms-title">TERMS & CONDITION</h1>
                        <p>&nbsp;</p>
                        <p><a href="http://www.getsetgig.com">GETSETGIG.COM</a> (THE “SITE”) AND RELATED PLATFORMS, PRODUCTS, AND SERVICES AVAILABLE ON OR FROM THE SITE (THE “SERVICES”) ARE OWNED AND OPERATED BY GETSETGIG (TOGETHER WITH ITS AFFILIATES, SUCCESSORS.</p>
            <p>THE SITE PROVIDES ONLINE BOOKING PLATFORM FOR ARTISTS, PERFORMERS, MUSICIANS, AGENTS, TALENT (REFERRED TO AS “ARTISTS”), AND EVENT PLANNERS AND ENTERTAINMENT/PERFORMANCE BUYERS OF ALL TYPES (REFERRED TO AS “CLIENT”).</p>
            <p>IN THESE TERMS AND CONDITIONS, THE WORDS “YOU”, “YOUR”, “MEMBER” AND “USER” REFERS TO ANY PERSON ACCESSING OR USING THE SITE (WHICH MAY IMPLY EITHER A ARTIST OR A CLIENT, AS THE CASE MAY BE), AND THE WORDS “WE”, “US”, AND “OUR” REFERS TO <a href="http://www.getsetgig.com">GETSETGIG</a>.</p>
            <p>THESE TERMS AND CONDITIONS FORM A VALID AND BINDING ELECTRONIC CONTRACT UNDER THE INFORMATION TECHNOLOGY ACT OF 2000 READ WITH RULES FRAMED THEREUNDER, BY AND BETWEEN <a href="http://www.getsetgig.com">GETSETGIG</a> AND THE ARTIST/USER.</p>
            <p>BY ACCESSING AND USING THE SITE AND THE SERVICES, YOU ACKNOWLEDGE AND AGREE TO BE BOUND BY THESE GENERAL TERMS AND CONDITIONS, OUR COPYRIGHT POLICY, PRIVACY POLICY, TRADEMARK POLICY, ABUSE POLICY, AND OUR SPECIFIC TERMS AND CONDITIONS APPLICABLE TO CERTAIN SERVICES .</p>
            <p>THESE TERMS AND CONDITIONS ARE LEGALLY BINDING AGREEMENTS. IF YOU USE THE SITE AND THE SERVICES ACTING AS THE REPRESENTATIVE FOR AN ARTIST, BAND, GROUP, COMPANY, OR ENTITY, YOU REPRESENT THAT YOU HAVE THE LEGAL AUTHORITY TO BIND SUCH INDIVIDUAL OR ENTITY AND YOU GUARANTEE COMPLIANCE BY SUCH INDIVIDUAL OR ENTITY WITH THESE TERMS AND CONDITIONS.</p>
            <p>WE RESERVE THE SOLE RIGHT AT ANY TIME TO MODIFY, DISCONTINUE, OR TERMINATE ANY SERVICE OR THE SITE, OR CHANGE, ADD, OR DELETE PORTIONS OF THESE TERMS AND CONDITIONS WITHOUT NOTICE. WE WILL POST CHANGES TO THESE TERMS AND CONDITIONS, IF ANY, TO THE SITE. IT IS YOUR RESPONSIBILITY TO CHECK THE SITE PERIODICALLY FOR CHANGES. YOUR CONTINUED USE OF THE SITE AND SERVICES AFTER ANY CHANGES CONSTITUTES YOUR ACCEPTANCE OF THE REVISED TERMS AND CONDITIONS.</p>
            <p>IF YOU DO NOT AGREE TO THESE TERMS AND CONDITIONS, DO NOT USE THE SITE OR SERVICES.</p>

            <ol className="terms-list">
                    <li><strong>USE OF SITE AND SERVICES:</strong>
                        <ol className="list-lower-alpha">
                            <li>Age Restriction. The Site and Services are intended for use by persons 18 years of age or older. The Site and Services are not intended for children under the age of 13. Children under the age 18 but at least 13 years of age may use the Site and Services only with the verifiable consent of a parent or legal guardian who has agreed to be bound by these Terms and Conditions.</li>
                            <li>Site Content Ownership. All materials and content on the Site and Services, including User Content (defined in Section below), (collectively, the “Site Content”) are the proprietary property of us or our licensors (including other users of the Site), including respective copyrights, logos, slogans, trademarks, and service marks. As between you and us, you shall retain all rights in your User Content subject to the licenses granted in these Terms and Conditions.</li>
                            <li>Site and Services Use License. Subject to these Terms and Conditions and only to the extent expressly permitted by the functionality of the Site and Services, you are granted a limited, non-exclusive, revocable, non-assignable, and non-transferable right to use the Site and Services and access and interact with Site Content. Except with respect to your use of certain Services in accordance with their specific terms and conditions that provide for or facilitate commercial activities, you understand that the Site and Site Content is for your personal &amp; commercial use only. Except as expressly permitted by these Terms and Conditions, the functionality of the Site, or your own use of your User Content (i) no Site Content may be modified, copied, distributed, framed, reproduced, republished, downloaded, displayed, posted, transmitted, sold, or otherwise used in any form or by any means, in whole or in part, and (ii) nothing herein should be construed as granting any license or right to use any Site Content, including trademarks, service marks, logos, slogans or taglines of us or artists, bands and third parties, or any software or code relating to the Site or Services.</li>
                        </ol>
                    </li>
                    <li><strong>TERMS AND CONDITIONS BETWEEN GETSETGIG AND THE ARTIST/USER</strong>
                        <ol className="list-lower-alpha">
                            <li>The engagement between the Artist (also referred to as 'You' and 'Your') and GETSETGIG is created to showcase and promote Artists on www.getsetgig.com (hereinafter referred to as "Website") to generate bookings for live performances.</li>
                            <li>The Artist is required to update availability directly or through his/her representative, manager or the management company on the Website. Once the calendar is updated the same can be used by GETSETGIG and the Customers to see the availability of the Artist for a live performance. The Artist can either accept or reject a booking request for a live performance through Website.</li>
                            <li>Artist shall visit the venue on the pre-agreed date for the live performance. The Artist is required to perform with reasonable skill and care and to a reasonable standard in accordance with recognized codes of practice. Artist shall be accompanied by GETSETGIG event manager or the Artist manager depending on the requirement by the Artist and or the booking Customer.</li>
                            <li>Artist is obliged to notify GETSETGIG in writing immediately in the event of illness or other unforeseen circumstances of any nature whatsoever resulting in the performance being cancelled or potentially not fulfilling the prior commitments at agreed date or time.</li>
                            <li>Cancellations have to be informed to GETSETGIG four (4) weeks prior to the booking event. Artist shall return the advance fee in full as agreed at the time of booking by You with GETSETGIG.</li>
                            <li>In the unlikely event of the GETSETGIG being forced to cancel, suspend, postpone or terminate the event on the Customer's request, GETSETGIG"s entire liability is to collect the advance paid [less 10% cancellation charges of the advance fee] to You and return it to the Customer. All correspondence done hereunder shall be done in writing through email.</li>
                            <li>GETSETGIG is not responsible for any misbehaviour on the part of the Customer and the Artist is solely responsible for his or her own safety. Your participation in any public or private event is at Your sole and exclusive risk. By using GETSETGIG You agree and understand that in connection with Your participation in any event or activity, You may be exposed to a variety of hazards and risks, foreseen or unforeseen, which can occur by natural causes or by the acts of other persons or third parties, either as a result of negligence or because of other reasons. You are personally responsible for all costs and risks associated with any public or private event or activity. GETSETGIG is not liable to any lawsuits, refund of money to You in case Customer finds Your behaviour and quality of performance substandard or below par or if You are not present for the event as per the Agreement with the Customer.</li>
                            <li>GETSETGIG has the right to record and upload the photos, videos, testimonials, interviews (hereinafter referred to as "Content") of the performance of the Artist on the Website to showcase and promote Your work in order to generate more bookings for You. The copyrights of such work shall be jointly owned by You and GETSETGIG. The Artist is solely responsible to the Content which is transmitted, posted, or distributed by You through GETSETGIG. GETSETGIG does not claim any permanent ownership of Content you submit or make available for inclusion on the engagement. GETSETGIG requires a limited license to host and display this Content, which lasts as long as you chose to host your work. The limited license is required to allow GETSETGIG to host, display, organize, and propagate an Artist"s body of work.</li>
                            <li>Artist acknowledges and agrees that the views expressed on the Website do not necessarily reflect the views of GETSETGIG and GETSETGIG does not support or endorse the User Content posted or submitted by any Artist or User.</li>
                            <li>You will not re–sell or re–offer any lead you receive through GETSETGIG to another Talent and/or Client (as the case may be), nor will you re–offer or post to any website any lead you receive through your relationship with this Site. You will be liable to compensate the company for the same.</li>
                            <li>ARTIST/CLIENT agrees to participate in all promotional activities of GETSETGIG for which the Talent shall be given prior notice. Talent agrees that GETSETGIG shall have the right to use its name, likeness and other material including photos and videos for promoting its Site and services. Talent shall promote GETSETGIG through its own online properties and links.</li>
                            <li>Users agree that GETSETGIG’s service charges become due upon a booking being made, and the same is not subject to any refund under any circumstances whatsoever (even if the event/performance stands cancelled due to any reason).</li>
                        </ol>
                    </li>
                    <li><strong>REGISTRATION:</strong>
                        <ol className="list-lower-alpha">
                            <li>In order to use certain parts of the Site and Services, you must register as a user and create an account on the Site. As part of the registration process, you will provide a username, password, email address, and other information and materials (the “Registration Information”) for your Site account. We may accept or reject your user registration in our sole discretion.</li>
                            <li>You alone are responsible for maintaining the security of your Registration Information and for all uses of the Site and Services in the name of your account. Upon registration, you will have a “Profile” page on the Site where you can manage your use of the Site and Services (your “Profile”).</li>
                            <li>You represent and warrant that all Registration Information will be true, accurate, complete, and current and that you will promptly update your Registration Information as necessary such that it is, at all times, true, accurate, complete, and current. We may use all Registration Information in accordance with our Privacy Policy.</li>
                        </ol>
                    </li>
                    <li><strong>CONTENT SUBMITTED BY YOU:</strong>
                        <ol className="list-lower-alpha">
                            <li><strong>User Content.</strong>
                                <ol className="list-lower-roman">
                                    <li>You are solely responsible for all materials and content that are submitted by you or through your account for posting, publication, display, distribution, performance, or other use on the Site or in connection with any Service, including without limitation, music, sound recordings, musical works, compositions, videos, photographs, pictures, graphics, names, likenesses, images, copyrights, trademarks, service marks, logos, biographical information, chat, messages, files, code, data, metadata, text, software, links, your Registration Information, content from your Third-Party Account, and any other information or materials.</li>
                                    <li>We are not responsible for any User Content that may be lost or unrecoverable through your use of the Site or Services, and you are encouraged to archive your User Content regularly and frequently.</li>
                                    <li>You must submit User Content to the Site and Services in compliance with our submission specifications. Our submission specifications are available on your Profile Page or otherwise on the Site. We reserve the right to refuse to accept and/or cause the removal of any User Content for any reason and at our sole discretion and without notice to you.</li>
                                    <li>As between you and us, and subject to our rights in these Terms and Conditions, you shall retain all rights in the User Content and nothing in these Terms and Conditions shall constitute a transfer to us of ownership of any User Content.</li>
                                    <li>You hereby acknowledge and agree that we may, at our sole discretion, disclose User Content in order to: (A) comply with law enforcement, court orders, or the legal process; (B) protect the rights and safety of individuals; or (C) settle disputes over intellectual property ownership. You understand and agree that in connection with the rights granted herein, we have the right, but no obligation, to remove, monitor, market, promote, advertise, or otherwise use your User Content.</li>
                                </ol>
                            </li>
                            <li><strong>Licenses to User Content.</strong>
                                <ol className="list-lower-roman">
                                    <li>By submitting User Content to the Site or in connection with any Service, you automatically grant to us a non-exclusive, transferable, royalty free, license throughout the universe, and in any manner and media now known or hereafter developed, to prepare, review, copy, reproduce, convert, host, distribute, transmit, stream, publicly perform, display, modify, adapt, excerpt (in whole or in part), publish, promote, advertise, market, create derivative works from, and otherwise use all or any portion of the User Content, and to grant and authorize sublicenses of the foregoing, in connection with the Site and Services and the functionality thereof; provided, however, we will not sell or otherwise commercially distribute for a fee User Content except in connection with your express use of a Service or program offered by us that provides such functionality. Except as may be specifically provided in connection with any particular Service, we have no obligation to pay you or anyone else any amounts, including record or publishing royalties, performance fees, license fees, or union, guild, or collective bargaining fees, for the distribution, public performance, or other uses of your User Content as authorized in these Terms and Conditions.</li>
                                    <li>The foregoing grant of rights includes, without limitation, our right to (but not obligation to):
                                        <ol className="list-lower-roman">
                                            <li>use User Content, including names, pictures, likenesses, images, voices, performances, biographical materials, and web links to websites that you control, in each case in connection with marketing, advertising, or promoting User Content, you, the Site, the Services, or us;</li>
                                            <li>submit or transmit User Content to third parties in connection with any applicable Services or program offered by us which you elect to use, in any format (e.g., MP3, streaming, or otherwise) in accordance with the functionality of such Service or program;</li>
                                            <li>edit or modify User Content in our sole discretion in connection with the Site, Services, or program offered by us and without any approval rights by you; and</li>
                                            <li>publicly perform and transmit your sound recordings and musical compositions in connection with the Site, Services, or a program offered by us, including, but not limited to, by interactive and non-interactive streaming on the Site or via a Service. If you have affiliated with a performance rights organization (“PRO”) with respect to your public performance rights, such as BMI, ASCAP, or SESAC, then you may be prohibited from granting the same rights to us, or a grant of public performance rights to us may prevent a PRO from collecting royalties on your behalf. In certain situations a PRO may require that you provide the PRO with notice if you are granting public performance rights to another party. If you have an agreement with a PRO that includes such a provision, you are solely responsible for providing such notice to the PRO. You understand that no fees or payment of any kind whatsoever shall be due to any PRO or music publisher for use of your User Content as authorized in these Terms and Conditions.</li>
                                        </ol>
                                    </li>
                                    <li>Without limitation of the rights granted herein, we and you may enter into additional agreements to confirm the rights granted herein, expand scope of rights granted to us, or otherwise with respect to the User Content, and to the extent such other agreements conflict with these Terms and Conditions, the terms of such other agreements shall control.</li>
                                    <li>Representations and Warranties. By submitting User Content to the Site or in connection with any Service, you acknowledge, represent, and warrant that:
                                        <ol className="list-lower-roman">
                                            <li>you own or control all necessary rights in and to the User Content, and you have the full right and authority to grant the rights, licenses, and permissions in these Terms and Conditions;</li>
                                            <li>the exercise of the rights granted by you herein shall not violate any laws or otherwise infringe upon the rights of any person or entity, including copyright, trademark, privacy, publicity, or other personal or proprietary rights, or contain libelous, defamatory or otherwise unlawful materials;</li>
                                            <li>the exercise of the rights granted by you herein shall be without any obligation to make any payment of any nature to you (except as expressly provided in connection with any Service) or any other person or entity;</li>
                                            <li>to the extent that you receive payments from us in connection with any Service, you acknowledge and agree that any such payments to you are inclusive of all payments otherwise due to any person or entity; and</li>
                                            <li>to the extent you do not own any underlying musical compositions, sound recordings, samples, publicity rights, or other materials or content in your User Content, it is your obligation to secure all appropriate permissions, clearances, licenses, or other authorizations and agreements, and, as applicable, to pay directly all third-party fees and royalties as may be required, including, but not limited to, with respect to artists, band members, authors, co-authors, copyright owners and co-owners, publishers, producers, or any other person who performed in the making of your User Content, and in connection with mechanical royalties, digital phonograph delivery royalties, public performance royalties, payments that may be required under any collective bargaining agreements or statutory schemes, or any other royalties, fees, and/or sums payable with respect to your User Content, and at our request you shall provide us with confirmation of such authorizations and payments.</li>
                                        </ol>
                                    </li>
                                </ol>
                            </li>
                        </ol>
                    </li>
                    <li><strong>INDEMNIFICATION:</strong>
                        <p>You agree to fully indemnify and hold us and our subsidiaries, affiliates, directors, officers, agents, contractors, partners, affiliates, employees, contractors, co-branders, advertisers, and other partners (collectively, the “Related Parties”) harmless, and upon our request, defend us and/or the Related Parties, from and against any and all losses, liabilities, damages, claims, costs, expenses, or demands (including reasonable lawyer' fees and costs), due to or arising out of (i) your use of the Site or Services; (ii) your violation or breach of any representation, warranties or other terms in these Terms and Conditions; (iii) your violation of any rights of any third party; and (iv) any dispute between you and any other user of the Site or Services. Without limitation, you agree to reimburse us and our Related Parties on demand for any payments made in resolution of any liability or claim that is subject to indemnification under this Section. We shall promptly notify you of any such claim, and you may assume control of the defense of such claim with counsel subject to our reasonable approval, provided that you obtain and post an appropriate bond for our benefit, and we shall have the right in all events to participate in the defense thereof. Your sole remedy as a result of any breach or alleged breach by us of these Terms and Conditions or other applicable terms and conditions or agreements is limited to your ability to discontinue use of the Site and your ability to terminate your participation in any Services in accordance with the terms thereof.</p>
                    </li>
                    <li><strong>LIMITATIONS AND DISCLAIMERS:</strong>
                        <p><strong>THE SITE, THE SERVICES, AND THE CONTENT THEREON ARE PROVIDED ON AN “AS-IS” AND “AS AVAILABLE” BASIS. WE MAKE NO, AND EXPRESSLY DISCLAIM ANY AND ALL, WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT. WE CANNOT GUARANTEE AND DO NOT PROMISE ANY SPECIFIC RESULTS FROM USE OF THE SITE AND/OR THE SERVICES.</strong> Without limiting the foregoing:</p>
                        <ol className="list-lower-alpha">
                            <li>We and the Related Parties are not responsible for any incorrect or inaccurate information in the Site Content. We and the Related Parties are not responsible for the content of, accuracy of, or statements or opinions expressed by third parties in any Site Content, including any User Content or in advertisements or solicitations. We are not responsible for the conduct, whether online or offline, of any user of the Site. Site Content is not investigated, monitored, or checked for accuracy or completeness by us. We do not make editorial decisions related to User Content. Inclusion of any Site Content, including links to other websites, does not imply approval or endorsement of the Site Content by us.</li>
                            <li>You understand the speculative nature of the music industry, and we make no guarantees whatsoever with respect to the marketing, promotion, acceptance, development, or popularity of you, your band, your music, or otherwise in connection with your use of the Site or Services; and we further make no guarantees whatsoever that any materials you create or distribute using our Site or Services, including your music, will achieve any results or be purchased or otherwise used by any third party.</li>
                            <li>The Site and the Services may be temporarily unavailable from time to time for maintenance or other reasons. We are not responsible for any error, omission, interruption, deletion, defect, delay in operation or transmission, communications line failure, theft or destruction or unauthorized access to, or alteration of, the Site or the Services. We are not responsible for any problems or technical malfunction of any telephone network or lines, computer online systems, servers or providers, computer equipment or software, or the failure of email on account of technical problems or traffic congestion on the Internet or at any web site or blocking from the destination mail servers, including injury or damage to any person's computer related to or resulting from participating or downloading materials in connection with the Site or the Services. Under no circumstances will we be responsible for any loss or damage, including personal injury or death, resulting from anyone's use of the Services, the Site, or any Site Content.</li>
                            <li>By using the Site and/or Services, you hereby release us and the Related Parties from claims, demands, and damages (actual and consequential) of every kind or nature, known or unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way related to your use of the Site and/or Services</li>
                            <li>IN NO EVENT WILL WE AND THE RELATED PARTIES BE LIABLE TO YOU FOR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL, OR PUNITIVE DAMAGES, INCLUDING DAMAGES FOR ANY LOST PROFITS AS A RESULT OF YOUR USE OF THE SITE OR SERVICES, EVEN IF WE ARE AWARE OR HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</li>
                        </ol>
                    </li>
                    <li><strong>CONFIDENTIALITY:</strong>
                        <p>You acknowledge and agree that in the course of using certain Services you may become aware of certain otherwise confidential information related to our business and business practices. Except to the extent that such information is otherwise generally available to third parties or is required to be divulged by operation of law, you agree to keep such information confidential.</p>
                    </li>
                    <li><strong>USAGE DATA:</strong>
                        <p>We may collect certain tracking and usage data generated or provided by users who visit or interact with your profile on the Site, or by users of products or other materials distributed in connection with your use of certain Services, including, but not limited to, personally identifiable information (“Usage Data”). We may provide all or part of the Usage Data to you. You agree to comply with all applicable laws with regard to your use of Usage Data. You will not transfer or disclose any Usage Data to any third party. We are not responsible for the accuracy of Usage Data, and we disclaim any and all liability relating thereto.</p>
                    </li>
                    <li><strong>NON – SOLICITATION:</strong>
                        <p>Users agree that they shall not exclude GETSETGIG and directly enter in to / laise with / solicit engagement from other Users who have been referred through / first contacted through or placed a request for quote through GETSETGIG’s Site. Users agrees that if the Client utilizes the services of a Talent whose referral was through GETSETGIG’s Site, within a period of nine months from the date of referral then in addition to other legal remedies, GETSETGIG shall be entitled to its service charge of 10%. Client and Talent agreed to be jointly and severally responsible for this promise and covenant. Without prejudice to the foregoing, it is the reasonable expectation of GETSETGIG that a Talent and a Client continue to route their future relationships through GETSETGIG.</p>
                    </li>
                    <li><strong>LINKS TO EXTERNAL SITES:</strong>
                        <p>GETSETGIG does not control the availability or content of any outside web sites, services, or resources to which this Site may link. Concerns regarding any such service, resource, or link should be directed to the particular outside service or resource. Unless stated otherwise, GETSETGIG does not endorse, sanction, or verify sites to which our Site links, and we provide these links merely for our Users’ convenience. Access to such other sites is at your own risk, and We disclaim all liability with regard to Your access to such linked web sites. In addition, We do not endorse, sanction, or verify sites that link to this Site, even if any logo or mark of GETSETGIG is used as part of the link to this Site.</p>
                    </li>
                    <li><strong>TERMINATION:</strong>
                        <ol className="list-lower-alpha">
                            <li>You may terminate your use of the Site at any time. You may terminate these Terms and Conditions with respect to any Service by removing your profile from Artist Database.</li>
                            <li>We may cancel your user registration and terminate your use of the Site or Services at any time with or without cause, in our sole discretion, and with or without notice. We have no obligation to monitor your use of the Site or Services.</li>
                            <li>We may delete any of your User Content, information, or other data from the Site or Services at any time, and we have no obligation to maintain copies of any deleted information.</li>
                            <li>Any provisions of these Terms and Conditions that by their nature should continue after termination of your use of the Site or any Services will continue to apply even after the expiration or termination of these Terms and Conditions or your use of the Site or any Services.</li>
                        </ol>
                    </li>
                    <li><strong>SUBMISSION OF MATERIALS AND OWNERSHIP:</strong>
                        <p>Recordings and all relevant information shall be submitted to us for Digital Distribution as Releases from your Profile in accordance with and subject to the General Terms and Conditions, and such submissions shall be deemed User Content and subject to all applicable representation, warranties, and agreements thereunder. Without limiting the foregoing, to the extent you do not own any underlying musical compositions, sound recordings, samples, publicity rights, or other materials or content in your User Content, it is your obligation to secure all appropriate permissions, clearances, licenses, or other authorizations and agreements, and, as applicable, to pay directly all third-party fees and royalties as may be required, including, but not limited to, with respect to artists, band members, authors, co-authors, copyright owners and co-owners, publishers, producers, or any other person who performed in the making of your User Content, and in connection with mechanical royalties, digital phonograph delivery royalties, public performance royalties, payments that may be required under any collective bargaining agreements or statutory schemes, or any other royalties, fees, and/or sums payable with respect to your User Content, and at our request you shall provide us with confirmation of such authorizations and payments.</p>
                    </li>
                    <li><strong>AUTHORIZATION:</strong>
                        <p>Without limitation of your grant of rights in the General Terms and Conditions, such rights include the right to Digitally Distribute all Recording(s) as Release(s) and to otherwise use the Recordings to the extent necessary to facilitate such Digital Distribution, including the rights to:</p>
                        <ol className="list-lower-alpha">
                            <li>reproduce, convert, and create derivative works of your Recordings and related materials for Digital Distribution of your Release(s);</li>
                            <li>reproduce, promote, advertise, market, sublicense, sell, publicly perform, display, host, distribute, deliver, transmit, and otherwise exploit and use Recordings and related materials for Digital Distribution of your Release(s);</li>
                            <li>display any and all lyrics associated with a musical composition embodied in any Recording in connection with the Digital Distribution of your Release(s);</li>
                            <li>use the name(s), voices(s), likeness(es), photograph(s), images, artwork, logos, trademarks, service marks, biographical materials, and other rights of publicity with respect to materials and information that you provide to us in connection with the Digital Distribution of your Release(s);</li>
                            <li>collect all income deriving from the Digital Distribution of your Release(s);</li>
                            <li>exercise all rights granted herein, including the right to edit and publicly perform Recordings and related materials consistent with industry- standards, for purposes of publicizing, promoting, marketing, and advertising the availability of the Recordings for Digital Distribution; and for purposes of creating ringtones, ring-back tones, or for other mobile uses, to the extent applicable for Digital Distribution; and</li>
                            <li>sublicense all rights granted in this Section to Retailers or other licensees.</li>
                        </ol>
                    </li>
                    <li><strong>MISCELLANEOUS:</strong>
                        <p>If any provision of these Terms and Conditions is held invalid or unenforceable, such provision shall be revised to the extent necessary to cure the invalidity or unenforceability, and the remainder of these Terms and Conditions shall continue in full force and effect. Nothing in these Terms and Conditions shall be deemed to confer any third-party rights or benefits. These Terms and Conditions, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by us without restriction. Our delay or failure to exercise any right or provision of these Terms and Conditions shall not constitute a waiver of such right or provision. These Terms and Conditions do not, and shall not be deemed to, constitute a partnership or joint venture between you and us, and neither you nor we, nor your or our respective directors, officers, employees, or agents shall, by virtue of the performance of the obligations under these Terms and Conditions, be deemed to be an agent or employee of the other, and neither you nor we has the authority to bind the other under any contract, agreement, or otherwise.</p>
                        <p>The Artist agrees that the laws of Government of India shall govern these Terms and Conditions. The exclusive jurisdiction for any claim or dispute with GETSETGIG shall be in the courts located in Mumbai, Maharashtra, India.</p>
                    </li>
                </ol>
                    </div>
                </div>
            </div>
        </div>
				</React.Fragment>
    )
}

export default TermsAndConditions;